# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build_and_Push
  displayName: Build and push image to dockerhub
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: Docker@2
      inputs:
        containerRegistry: 'Raguraman Sirius docker'
        repository: 'fiveout/iha_poc'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
    - publish: '$(Build.SourcesDirectory)/manifests'
      artifact: manifests
    - task: KubernetesManifest@0
      inputs:
        action: 'bake'
        namespace: 'dummy'
        containers: 'nevermind'
        helmChart: 'ihahelmpoc/.'
        releaseName: 'firsthelmrelease'
        overrides: 'dockerImageTagName=$(Build.BuildId)''



# - stage: Helm_bake_and_deploy
#   displayName: Helm bake and deploy to openshift
#   jobs:
#   - job: Deploy
#     displayName: Helm deploy
#     pool:
#       vmImage: ubuntu-latest
#     steps:
    
    

  # displayName: 'Deploy the container to openshift'
  # dependsOn: Build_and_Push
  # jobs:
  # - deployment: Deploy
  #   displayName: Deploy
  #   pool:
  #     vmImage: 'ubuntu-20.04'
  #   environment: 'raguraman-sirius-stage'
  #   #variables:
  #   #- group: Release
  #   strategy:
  #     runOnce:
  #       deploy:
  #         steps:
  #         - download: current
  #           artifact: manifests
  #         - task: KubernetesManifest@0
  #           displayName: Deploy to Kubernetes cluster
  #           inputs:
  #             action: deploy
  #             kubernetesServiceConnection: 'openshift-sandbox-raguraman-sirius-stage-1650458998345'
  #             namespace: 'raguraman-sirius-stage'
  #             manifests: |
  #               $(Pipeline.Workspace)/manifests/deployment.yml
  #               $(Pipeline.Workspace)/manifests/services.yml