# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build_and_Push
  displayName: Build and push image to dockerhub
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: Docker@2
      inputs:
        containerRegistry: 'Raguraman Sirius docker'
        repository: 'fiveout/iha_poc'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
    - publish: '$(Build.SourcesDirectory)/helm'
      artifact: helm
    

- stage: 'Dev_Deployment'
  displayName: 'Deploy the container to openshift - dev'
  dependsOn: Build_and_Push
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-20.04'
    environment: 'iha-poc-dev'
    #variables:
    #- group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: helm
          - task: HelmDeploy@0
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: 'openshift-sandbox-raguraman-sirius-stage-1650458998345'
              namespace: 'raguraman-sirius-stage'
              command: 'upgrade'
              chartType: 'Name'
              chartName: '$(Pipeline.Workspace)/helm/ihahelmpoc/.'
              releaseName: 'release-dev'
              overrideValues: 'dockerImageTagName=$(tag)'
              valueFile: '$(Pipeline.Workspace)/helm/ihahelmpoc/values/values-dev.yaml'
          - publish: '$(Pipeline.Workspace)/helm'
            artifact: helm
            
- stage: 'Prod_Deployment'
  displayName: 'Deploy the container to openshift - prod'
  dependsOn: Dev_Deployment
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-20.04'
    environment: 'iha-poc-prod'
    #variables:
    #- group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: helm
          - task: HelmDeploy@0
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: 'openshift-sandbox-raguraman-sirius-stage-1650458998345'
              namespace: 'raguraman-sirius-stage'
              command: 'upgrade'
              chartType: 'Name'
              chartName: '$(Pipeline.Workspace)/helm/ihahelmpoc/.'
              releaseName: 'release-prod'
              overrideValues: 'dockerImageTagName=$(tag)'
              valueFile: '$(Pipeline.Workspace)/helm/ihahelmpoc/values/values-prod.yaml'