# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build_and_Push
  displayName: Build and push image to dockerhub
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: Docker@2
      inputs:
        containerRegistry: 'Raguraman Sirius docker'
        repository: 'fiveout/iha_poc'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
    - publish: '$(Build.SourcesDirectory)/manifests'
      artifact: manifests
    - task: KubernetesManifest@0
      inputs:
        action: 'bake'
        namespace: 'dummy'
        containers: 'nevermind'
        helmChart: 'ihahelmpoc/.'
        releaseName: 'firsthelmrelease'
        overrides: 'dockerImageTagName=$(Build.BuildId)'