apiVersion : apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: https://hub.docker.com/repository/docker/raguramansirius/iha_poc
          ports:
          - containerPort: 3000
