apiVersion: v1
kind: Service
metadata:
  name: external-expose-service
  namespace: raguraman-sirius-stage
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
  
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: external-route
  namespace: raguraman-sirius-stage
spec:
  path: /
  to:
    kind: Service
    name: external-expose-service
  port:
    targetPort: 80
