apiVersion: v1
kind: Service
metadata:
    name: webloadbalancer
spec:
    type: LoadBalancer
    ports:
    - port: 80 
      targetPort: 3000
    selector:
        app: web

---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: web
spec:
  to:
    kind: Service
    name: web
    weight: 100
  port:
    targetPort: 3000
  wildcardPolicy: None
