apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.exposeServiceName }}
  namespace: {{ .Values.clusterNamespace }}
spec:
  selector:
    app: {{ .Values.containerAppName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.containerPort }}

---
  
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.exposeRouteName }}
  namespace: {{.Values.clusterNamespace}}
spec:
  path: /
  to:
    kind: Service
    name: {{ .Values.exposeServiceName }}
  port:
    targetPort: {{ .Values.containerPort }}
